# Generated by Django 6.0 on 2026-02-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sealed_priduct',
            new_name='sealed_product',
        ),
    ]
