# Generated by Django 6.0.1 on 2026-02-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_sealed_priduct_purchase_sealed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tcgapis_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tcgapis_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
