# Generated by Django 6.0 on 2026-02-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_card_tcgapis_group_id_card_tcgapis_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgApisCardIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(db_index=True)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('group_id', 'number')},
            },
        ),
    ]
