# Generated by Django 6.0 on 2026-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tcgapiscardindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ptcg_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_image_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_rarity',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_set_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ptcg_set_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
