# Generated by Django 6.0 on 2026-02-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_card_ptcg_id_card_ptcg_image_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('set_id', models.CharField(db_index=True, max_length=80)),
                ('set_name', models.CharField(db_index=True, max_length=255)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('rarity', models.CharField(blank=True, max_length=100, null=True)),
                ('image_small', models.URLField(blank=True, null=True)),
                ('image_large', models.URLField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['set_name', 'number'], name='tracker_car_set_nam_c9653f_idx')],
                'unique_together': {('set_id', 'number')},
            },
        ),
    ]
