# Generated by Django 6.0 on 2026-02-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_cardcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.cardcatalog'),
        ),
    ]
