# Generated by Django 6.0 on 2026-02-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_card_catalog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardcatalog',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='cardcatalog',
            index=models.Index(fields=['set_id', 'number'], name='tracker_car_set_id_635875_idx'),
        ),
    ]
