# Generated by Django 6.0 on 2026-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_cardcatalog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='catalog_id_str',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
