# Generated by Django 6.0 on 2026-02-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_card_catalog_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, default='')),
                ('tcgcsv_url', models.URLField(blank=True, default='')),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('rarity', models.CharField(blank=True, default='', max_length=80)),
                ('printing', models.CharField(blank=True, default='Normal', max_length=60)),
                ('is_sealed', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_id', 'printing'), name='uniq_product_printing')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direct_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(default='tcgcsv', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tracker.catalogitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'captured_at'), name='uniq_item_captured_at')],
            },
        ),
    ]
