# Generated by Django 6.0 on 2026-02-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_marketprice_source_catalogitem_pricesnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='price_each',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sealedproduct',
            name='product_type',
        ),
        migrations.AddField(
            model_name='card',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cards', to='tracker.catalogitem'),
        ),
        migrations.AddField(
            model_name='card',
            name='printing',
            field=models.CharField(blank=True, default='Normal', max_length=64),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sealedproduct',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sealed', to='tracker.catalogitem'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sealedproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sealedproduct',
            name='set_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
