# Generated by Django 6.0 on 2026-02-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_price_purchase_price_each_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealedproduct',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.catalogitem'),
        ),
        migrations.AlterField(
            model_name='sealedproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sealedproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sealedproduct',
            name='set_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
