# Generated by Django 6.0 on 2026-02-04 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_sealedproduct_catalog_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ptcg_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_image_large',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_image_small',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_rarity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_set_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ptcg_set_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tcgapis_group_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tcgapis_product_id',
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sealedproduct',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sealed_products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
